### ISSUE TITLE
Userdata shall be applied to callback function in Source::IO

### ISSUE THREAD

**Issue by LeeTroy** [openbmc/sdeventplus#2]
SDBusPlus is quite easy and useful to deal with I/O multiplexing in C++.

Currently, the callback function will only have the file descriptor and the event.
https://github.com/openbmc/sdeventplus/blob/9ce0d10bd5f10c9aa218817df879388d7d169379/src/sdeventplus/source/io.hpp#L20

The userdata in `sd_event_add_io` is being applied with nullptr at this point.
https://github.com/openbmc/sdeventplus/blob/9ce0d10bd5f10c9aa218817df879388d7d169379/src/sdeventplus/source/io.cpp#L67-L74

It would be more useful if the callback function could have that userdata.

PS. Is here the right place to discuss the design? Or should I post on mailing list?

Thanks,
Troy Lee

**Comment by wak-google** [comment]
This is the right place to ask sdeventplus questions.

The reason it was designed this way was because std::functions can have arbitrary data and references bound to them, so you don't need to pass a separate untyped userdata pointer to them. sdeventplus is meant to hide that detail while still giving you flexibility. You can create an sdeventplus IO object with a callback that has outside data bound into it with lambda captures or std::bind.

You could have something like
```
struct MyData;

void addHandler(const sdeventplus::Event &event, int fd, MyData&& myData)
{
    sdeventplus::source::IO(event, fd, EPOLLIN | EPOLLET, [myData = std::move(myData)](sdeventplus::source::IO&, int, uint32_t) {
        doAcrion();
    });
}
```

**Comment by wak-google** [comment]
Also, if you would like to be able to use floating sources for anything, I have a patchset out to implement that.
https://gerrit.openbmc-project.xyz/c/openbmc/sdeventplus/+/19953/3

**Comment by LeeTroy** [comment]
Wow, I totally forgot I could use capture with lambda function. 
Thanks for quick response!!
